258: Enabler editing campaign riders
bikebrigade/dispatch pull request #259
Opened 2023-11-15 14:52 UTC by teesloane

Closes #258 

This set of commits makes the following changes:

- add a route to allow the editing of a rider
- update the AddRiderFormComponent to be able to _edit_ riders. 
- rename the AddRiderFormComponent -> CampaignRiderFormComponent
- Update the RiderSelectionComponent to have an update callback (not sure if this is right, but I'm not sure if the same logic is possible in `mount`.)
- Add Tests 

## Screencap of the changes

https://github.com/bikebrigade/dispatch/assets/12987958/b5b7825d-e457-4773-97ac-3ab95997e5fd

2023-12-18 21:41 UTC, mveytsman requested changes
Love it!

Small change around the broadcast / handling of the update campaign rider event.

2023-12-18 21:41 UTC, mveytsman commented on lib/bike_brigade/delivery.ex
> +    |> broadcast(:campaign_updated)
Move closer to create_campaign rider
Note we're broadcasting `:campaign_updated` should be `:campaign_rider_udated`

Update the handle_info to do the same as `:campaign_rider_created`

2023-12-20 18:56 UTC, teesloane commented
Fixed and ready for re-review!

2024-01-02 20:09 UTC, mveytsman approved these changes

2024-01-03 14:17 UTC, merged