[140] - Rider campaign signup
bikebrigade/dispatch pull request #263
Opened 2023-12-12 00:44 UTC by teesloane

Closes #140. Commits are atomic and go into more detail. 

https://github.com/bikebrigade/dispatch/assets/12987958/d39ed6b2-fb32-4292-8d95-42ae93985cd9

2023-12-12 01:16 UTC, teesloane commented on lib/bike_brigade_web/live/campaign_signup_live/show.html.heex
> +    <:col :let={task} label="Dropoff Location"><%= task.dropoff_location.address %></:col>
Right now this shows the exact address of the Task. Is this what we want?

2024-01-02 20:36 UTC, mveytsman requested changes
* When singing up, riders shouldn't see exact location of the task
	- Switch to showing neighbourhood or abstracted location 
* bug about navigating via "back button" when rider signs up for themselves
* leave a note on `campaign_signup_live/index.ex` about the database fetching
* "Campaign Filled" should be no colour?
* Remove rider signup form - so just click and it does it.
* Remove "capacity" and "pickup window" from rider signup form
	* Maybe remove enter buildings
* consider adding a rider setting that enables people to choose how much of their PI is shown when singing up
	- nick name, full name, etc

2024-01-02 20:36 UTC, mveytsman commented on lib/bike_brigade_web/live/campaign_signup_live/show.ex
> +    # if a task or a campaign rider changes (ie, if any of hte broadcasted_infos)
typo

2024-01-05 20:27 UTC, mveytsman approved these changes
🎉

2024-01-05 21:53 UTC, merged