fix: remove date filter when fetching campaign_ids
bikebrigade/dispatch pull request #387
Opened 2024-06-12 20:31 UTC by teesloane

fixes #369 

This is a draft PR until I can test it sunday night.

## Describe your changes

- when list_campaigns is called with an option of `campaign_ids`, we disable filtering by start/end date.

@mveytsman any ideas on how I could write a test for this that simulates that it's a sunday locally and the campaigns in question are on a monday (without changing the system under test?)

## Checklist before requesting a review

- [ ] I have performed a self-review of my code
- [ ] If it is a core feature, I have added tests.
- [ ] Are there other PRs or Issues that I should link to here?
- [ ] Will this be part of a product update? If yes, please write one phrase
      about this update in the description above.

2024-06-12 20:32 UTC, teesloane commented
Also, I added some needed padding on desktop.

![image](https://github.com/bikebrigade/dispatch/assets/12987958/40c7196f-fdfc-4d72-ae64-6b9f57c0631a)

(`1` is from before, `2` is after)

2024-06-17 22:20 UTC, mveytsman approved these changes
Love how simple it is - i do want to refactor this into a `with` (happy to pair!)

2024-06-17 22:20 UTC, mveytsman commented on lib/bike_brigade/delivery.ex
> +      # First we check if we are fetching with campaign_ids
I love this but I feel we can refactor this into a `with`

Happy to pair on it!

2024-06-17 22:20 UTC, mveytsman requested changes
oops meant to not approve it 🐵

2024-06-21 15:20 UTC, mveytsman approved these changes

2024-06-24 16:37 UTC, mveytsman commented
Did it work?

2024-06-24 18:02 UTC, teesloane commented
> Did it work?

I forgot to test yesterday 🙃

2024-07-20 03:29 UTC, mveytsman commented
@teesloane is this good to go?

2024-07-23 00:20 UTC, teesloane commented
sorry, it's been a while and I forgot about this. I need to revisit the code to make sure I feel confident. I'll aim to merge it in on the weekend :)

2024-07-28 15:00 UTC, merged